#!/usr/bin/env python3
"""Procedural sound design for the first-boot cinematic of 404: Alive.
Writes 16-bit mono 22.05 kHz WAVs (prefix `cine_`) into assets/sounds/. Requires numpy + scipy.
It is separate from generate_audio.py so the in-game sounds are never regenerated by accident.

The score (`cine_music`) is timed to the cinematic timeline in scripts/cinematic/cine_art.gd:
    0.0 forest  | 11.7 interior | 20.4 lamp flickers | 21.0 POWER CUT | 24.0 PC wakes
    24.6 text   | 27.4 logo     | 30.0 glitch        | 31.6 pulled in | 39.6 impact | 40.0 end
Loops (night, room, keys) are built from whole cycles / circular FFT filtering so they loop seamlessly."""
import os, wave
import numpy as np
from scipy.signal import fftconvolve

SR = 22050
OUT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "sounds"))
rng = np.random.default_rng(404)
LOUD = {}

def T(d): return np.arange(int(SR * d)) / SR
def sine(f, d): return np.sin(2 * np.pi * f * T(d))
def sweep(f0, f1, d):
    t = T(d); f = f0 * (f1 / f0) ** (t / d); return np.sin(2 * np.pi * np.cumsum(f) / SR)
def saw(f, d): return 2 * ((f * T(d)) % 1) - 1
def noise(d): return rng.uniform(-1, 1, int(SR * d))
def env(d, a=0.004, k=8.0):
    t = T(d); return np.minimum(t / a, 1) * np.exp(-k * t)
def bpg(x, fc, bw=0.5):
    X = np.fft.rfft(x); f = np.fft.rfftfreq(len(x), 1 / SR) + 1e-3
    return np.fft.irfft(X * np.exp(-0.5 * ((np.log(f) - np.log(fc)) / bw) ** 2), len(x))
def lp(x, fc):
    X = np.fft.rfft(x); f = np.fft.rfftfreq(len(x), 1 / SR)
    return np.fft.irfft(X / (1 + (f / fc) ** 4), len(x))
def hp(x, fc):
    X = np.fft.rfft(x); f = np.fft.rfftfreq(len(x), 1 / SR)
    return np.fft.irfft(X * (1 - 1 / (1 + (f / fc) ** 4)), len(x))
def norm(x, peak=0.85): return x / max(np.abs(x).max(), 1e-9) * peak
def fit(x, n):
    return x[:n] if len(x) >= n else np.concatenate([x, np.zeros(n - len(x))])
def mix(parts, d):
    out = np.zeros(int(SR * d))
    for off, x in parts:
        i = int(SR * off); n = min(len(x), len(out) - i)
        if n > 0: out[i:i + n] += x[:n]
    return out
def fade(x, a=0.0, b=0.0):
    x = x.copy()
    if a > 0: n = min(int(SR * a), len(x)); x[:n] *= np.linspace(0, 1, n)
    if b > 0: n = min(int(SR * b), len(x)); x[-n:] *= np.linspace(1, 0, n)
    return x
def interp(points, n):
    t = np.arange(n) / SR; xs, ys = zip(*points); return np.interp(t, xs, ys)

def reverb(x, rt=2.4, wet=0.4, damp=3200, pre=0.02):
    n = int(SR * rt)
    ir = rng.normal(size=n) * np.exp(-6.9 * np.arange(n) / n)
    ir = lp(ir, damp); ir /= np.sqrt((ir ** 2).sum()) + 1e-9
    ir = np.concatenate([np.zeros(int(SR * pre)), ir])
    y = fftconvolve(x, ir)
    dry = np.concatenate([x, np.zeros(len(y) - len(x))])
    return dry * (1 - wet) + y * wet

def save(name, x, loop=False, peak=0.85):
    x = norm(np.nan_to_num(x), peak)
    if not loop:
        n = min(int(SR * 0.006), len(x) // 2); x[-n:] *= np.linspace(1, 0, n)
        n = min(int(SR * 0.002), len(x) // 2); x[:n] *= np.linspace(0, 1, n)
    with wave.open(os.path.join(OUT, name + ".wav"), "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes((np.clip(x, -1, 1) * 32767).astype("<i2").tobytes())
    LOUD[name] = (len(x) / SR, float(np.abs(x).max()), float(np.sqrt((x ** 2).mean())))

def loopable(x, xf):
    """cross-fade the tail into the head so the sample loops without a click"""
    n = int(SR * xf); body = x[:-n].copy()
    body[:n] = body[:n] * np.linspace(0, 1, n) + x[-n:] * np.linspace(1, 0, n)
    return body

def circ_noise(d, fc, bw=0.5):
    """noise that is exactly periodic over d seconds (circular FFT filter)"""
    return bpg(noise(d), fc, bw)

# ============================================================================================ building blocks
def tone(f, d, harm=(1.0, 0.45, 0.2, 0.1), detune=0.0025, vib_hz=0.23, vib_amt=0.004):
    t = T(d); out = np.zeros_like(t)
    for k, a in enumerate(harm, 1):
        for dv in (-detune, 0.0, detune):
            out += a * np.sin(2 * np.pi * f * k * (1 + dv) * t + rng.random() * 6.28 + vib_amt * k * np.sin(2 * np.pi * vib_hz * t))
    return out / (len(harm) * 3 * 0.45)

def musicbox(f, d=3.0, cents=0.0):
    f = f * 2 ** (cents / 1200); t = T(d)
    x = (np.sin(2 * np.pi * f * t) * np.exp(-2.0 * t) + 0.45 * np.sin(2 * np.pi * f * 2.0 * t) * np.exp(-4.5 * t)
         + 0.2 * np.sin(2 * np.pi * f * 3.01 * t) * np.exp(-7 * t) + 0.12 * np.sin(2 * np.pi * f * 5.4 * t) * np.exp(-11 * t))
    return x * np.minimum(t / 0.002, 1) + 0.15 * hp(noise(d), 3500) * env(d, 0.0005, 160)

def heart(gain=1.0, pitch=1.0):
    a = sweep(78 * pitch, 38 * pitch, 0.22) * env(0.22, 0.003, 14)
    b = sweep(64 * pitch, 34 * pitch, 0.2) * env(0.2, 0.003, 15) * 0.7
    return gain * mix([(0.0, a), (0.27, b)], 0.55)

def bitcrush(x, bits=5, hold=6):
    q = 2 ** bits; y = np.round(x * q) / q
    return np.repeat(y[::hold], hold)[:len(x)]

# ============================================================================================ the score
D = 40.0
N = int(SR * D)
M = np.zeros(N)           # dry bed (pads, drones)
MB = np.zeros(N)          # music box (gets its own reverb)
FX = np.zeros(N)          # stingers / textures

def put(buf, x, t0, g=1.0):
    i = int(SR * t0); n = min(len(x), N - i)
    if n > 0 and i >= 0: buf[i:i + n] += x[:n] * g

def padnote(f, t0, t1, g, harm=(1.0, 0.45, 0.2, 0.1), fc=1400, att=2.5, rel=2.5):
    d = (t1 - t0) + 0.2
    x = lp(tone(f, d, harm), fc)
    put(M, fade(x, att, rel), t0, g)

# ---- 0..11.8  night forest: a held A drone, an airy minor pad that breathes in, a faltering music box
padnote(55.0, 0.0, 14.0, 0.55, harm=(1.0, 0.5, 0.25), fc=300, att=4.0, rel=3.0)
padnote(110.0, 1.0, 14.0, 0.30, harm=(1.0, 0.4), fc=400, att=5.0, rel=3.0)
for f, t0 in [(220.0, 2.5), (329.6, 3.5), (523.3, 5.5)]:               # A3, E4, C5: the cold minor chord
    padnote(f, t0, 13.0, 0.18, harm=(1.0, 0.3, 0.1), fc=1600, att=4.0, rel=3.0)
phrase = [(659.3, 2.2, 0), (784.0, 3.9, 0), (880.0, 6.1, -30), (784.0, 7.3, 0), (659.3, 8.8, 0), (587.3, 10.4, -45)]   # E5 G5 A5 G5 E5 D5, a little out of tune
for f, t0, c in phrase:
    put(MB, musicbox(f, 3.2, c), t0, 0.55)

# ---- 11.7..20.9  inside, warmer and lower: F major seventh under the same drone, a slow body-heat pulse
padnote(87.3, 11.0, 21.0, 0.34, harm=(1.0, 0.5, 0.3), fc=420, att=2.5, rel=0.06)       # F2
padnote(130.8, 11.5, 21.0, 0.22, harm=(1.0, 0.4), fc=600, att=2.5, rel=0.06)           # C3
padnote(164.8, 12.0, 21.0, 0.20, harm=(1.0, 0.3), fc=900, att=3.0, rel=0.06)           # E3
padnote(220.0, 12.5, 21.0, 0.16, harm=(1.0, 0.3), fc=1100, att=3.0, rel=0.06)          # A3
padnote(55.0, 11.0, 21.0, 0.50, harm=(1.0, 0.5, 0.25), fc=300, att=1.0, rel=0.06)
for f, t0, c in [(698.5, 13.6, 0), (659.3, 16.2, -20), (523.3, 18.9, -40)]:
    put(MB, musicbox(f, 3.0, c), t0, 0.5)
for k, t0 in enumerate(np.arange(15.0, 20.4, 1.7)):
    put(FX, heart(0.28 + 0.07 * k), float(t0))

# ---- 21.0 power cut: the score is torn out. Silence, then a sub swell creeps back in
for buf in (M, MB):
    buf[int(SR * 20.96):int(SR * 22.1)] *= np.linspace(1, 0, int(SR * 22.1) - int(SR * 20.96)) ** 8
put(FX, sweep(46, 28, 1.6) * env(1.6, 0.4, 1.4), 21.7, 0.7)

# ---- 22..30  dread: a tritone cluster that beats against itself, panic heartbeats, a high thread of sound
dread = [(55.0, 22.0, 0.50), (58.27, 22.4, 0.36), (82.4, 22.8, 0.26), (123.5, 23.0, 0.18), (185.0, 23.4, 0.12)]
for f, t0, g in dread:
    padnote(f, t0, 31.0, g, harm=(1.0, 0.6, 0.35, 0.2), fc=700, att=3.5, rel=1.5)
hi = sine(932.3, 9.0) * (0.6 + 0.4 * np.sin(2 * np.pi * 0.31 * T(9.0)))
put(M, fade(lp(hi, 2000), 3.0, 1.0), 22.5, 0.045)
beats = []
tb = 22.2; gap = 1.05
while tb < 31.4:
    beats.append(tb); tb += gap; gap = max(0.46, gap - 0.045)
for k, tb in enumerate(beats):
    put(FX, heart(0.5 + 0.03 * k, 1.0), tb)
# 24.0 PC wakes: a low stab swells in under a rake of metal
stab = sum(lp(saw(f, 3.2), 520) * 0.5 for f in (55.0, 55.4, 82.5, 110.7))
put(M, stab * np.sin(np.pi * np.linspace(0, 1, len(stab))) ** 1.5, 24.0, 0.42)
scrape = bpg(noise(3.0), 2600, 0.35) * np.sin(np.pi * T(3.0) / 3.0) ** 2 * (0.6 + 0.4 * np.sin(2 * np.pi * 11 * T(3.0)))
put(FX, scrape, 24.0, 0.16)
# 27.4 logo: a reversed bell, then the floor drops out
rb = musicbox(466.2, 3.0)[::-1] * np.linspace(0.2, 1, int(SR * 3.0)) ** 2
put(FX, rb, 25.0, 0.5)
put(FX, sweep(120, 34, 2.2) * env(2.2, 0.01, 1.4), 27.4, 0.8)

# ---- 30..38.4  glitch: the pad is gated on and off at random, bitcrushed; a Shepard-ish climb underneath
gate_t = np.arange(int(SR * 8.4)) / SR
gate = np.zeros_like(gate_t); pos = 0.0
while pos < 8.4:
    seg = rng.uniform(0.04, 0.2); on = rng.random() < 0.62
    gate[(gate_t >= pos) & (gate_t < pos + seg)] = 1.0 if on else 0.0; pos += seg
bed = lp(tone(110.0, 8.5, (1, 0.7, 0.5, 0.3)) + tone(116.5, 8.5, (1, 0.6, 0.4)), 2400)[:len(gate)]
bed = bitcrush(bed, 5, 5) * gate * np.linspace(0.3, 1.0, len(gate)) ** 1.4
put(M, bed, 30.0, 0.55)
t8 = T(8.4)
for k in range(4):   # a Shepard-style climb: four octave-spaced voices that rise and cross-fade, never arriving
    pos = ((k + t8 / 8.4) / 4.0) % 1.0
    fr = 55.0 * 2 ** (4.0 * pos)
    x = np.sin(2 * np.pi * np.cumsum(fr) / SR) * np.sin(np.pi * pos) ** 2
    put(FX, x * np.linspace(0.1, 1, len(t8)) ** 2, 30.0, 0.10)
for tg in (30.0, 31.3, 32.2, 33.6, 35.0):
    put(FX, bitcrush(musicbox(float(rng.choice([440, 622, 880, 1244])), 0.9), 4, 8), tg, 0.35)

# ---- 38.4..40  one enormous swell, then a hard cut to silence so the impact (cine_impact) lands alone
swell = lp(noise(1.3), 6000) * np.linspace(0, 1, int(SR * 1.3)) ** 3
put(FX, swell, 38.3, 0.5)
put(M, lp(saw(55.0, 1.3) + saw(110.5, 1.3), 900) * np.linspace(0, 1, int(SR * 1.3)) ** 2, 38.3, 0.5)
cut = int(SR * 39.55)
for buf in (M, MB, FX):
    buf[cut:] = 0.0

music = reverb(M, 2.6, 0.38, 2600)[:N] + 1.25 * reverb(MB, 3.2, 0.55, 5000)[:N] + FX
music = np.tanh(1.3 * music)
# Master dynamics, applied AFTER the reverb so the silences are real: a hush that builds through the forest and the
# room, a hard drop at the power cut, a slow climb through the panic, the glitch and the pull, then a hard stop.
db_pts = [(0.0, -30), (5.0, -22), (11.7, -17), (12.5, -16), (20.4, -14), (20.9, -13), (20.97, -80), (21.7, -80),
          (22.6, -24), (24.0, -18), (27.4, -14), (30.0, -10), (36.0, -5), (38.3, -2), (39.5, 0), (39.55, -80), (40.0, -80)]
music = music * 10 ** (interp(db_pts, len(music)) / 20.0)
save("cine_music", music, peak=0.85)

# ============================================================================================ ambience loops
# night forest: wind, a bed of crickets, a distant frog-like knock; exactly periodic
d = 10.0
wind_n = lp(circ_noise(d, 380, 0.9), 700) * (0.55 + 0.45 * np.sin(2 * np.pi * T(d) / d * 2 + 1.0))
t = T(d)
crick = np.zeros_like(t)
for f0, rate, ph in [(4300, 31, 0.0), (4650, 27, 1.3), (3950, 34, 2.1)]:
    chirp = np.sin(2 * np.pi * f0 * t) * np.clip((np.sin(2 * np.pi * rate * t + ph) - 0.2) * 3.0, 0.0, 1.0)
    burst = np.clip((np.sin(2 * np.pi * (4.0 / d) * t + ph) + 0.4) * 2.0, 0.0, 1.0)
    crick += chirp * burst
crick *= 0.05
night = wind_n * 1.0 + crick
save("cine_night", night, loop=True, peak=0.6)

# room tone: mains hum (whole cycles), PC fan, tiny drive ticks
d = 4.0
t = T(d)
hum = sum(a * np.sin(2 * np.pi * f * t) for f, a in [(100.0, 1.0), (200.0, 0.5), (300.0, 0.25), (50.0, 0.35)]) * 0.35
fan = lp(circ_noise(d, 900, 0.8), 1800) * 0.7
ticks = np.zeros_like(t)
for tt in (0.7, 1.35, 2.9):
    i = int(SR * tt); ticks[i:i + 220] += (rng.uniform(-1, 1, 220) * np.exp(-np.arange(220) / 28.0)) * 0.5
save("cine_room", hum + fan + ticks, loop=True, peak=0.6)

# mechanical keyboard, a person typing: irregular bursts of clicks, each with a low thock
d = 4.0
keys = np.zeros(int(SR * d))
def keystroke(lo=1.0):
    n = int(SR * 0.09)
    click = hp(rng.uniform(-1, 1, n), 1800) * np.exp(-np.arange(n) / 90.0)
    thock = sine(150 * lo * rng.uniform(0.9, 1.15), 0.09) * env(0.09, 0.001, 55) * 0.8
    return (click * 0.9 + thock) * rng.uniform(0.6, 1.0)
tt = 0.05
while tt < d - 0.15:
    burst = rng.integers(4, 9)
    for _ in range(burst):
        if tt > d - 0.15: break
        k = keystroke(); i = int(SR * tt); keys[i:i + len(k)] += k[:len(keys) - i]
        tt += rng.uniform(0.07, 0.17)
    tt += rng.uniform(0.25, 0.5)
save("cine_keys", keys, loop=True, peak=0.7)

# ============================================================================================ one-shots
# owl: two soft hoots, far away
hoot = lambda f: lp(sine(f, 0.55) * np.sin(np.pi * T(0.55) / 0.55) ** 1.4 * (1 + 0.04 * np.sin(2 * np.pi * 6 * T(0.55))), 900)
owl = mix([(0.0, hoot(430)), (0.75, hoot(395) * 0.9)], 1.7)
save("cine_owl", reverb(owl, 1.8, 0.5, 1800)[:int(SR * 3.2)])

# power cut: the lamp buzzes up, arcs, a relay thunks, everything spins down
d = 3.4
t = T(d)
lamp = sum(sine(f, d) * a for f, a in [(100, 1.0), (200, 0.6), (300, 0.4)]) * np.interp(t, [0, 0.3, 0.42, 0.5, 0.6], [0.2, 1.0, 0.4, 1.0, 0.0])
crack = np.zeros_like(t)
for tt in (0.36, 0.43, 0.5, 0.53):
    n = int(SR * 0.08); i = int(SR * tt)
    crack[i:i + n] += hp(rng.uniform(-1, 1, n), 1500) * np.exp(-np.arange(n) / 160.0) * rng.uniform(0.6, 1.0)
thunk = mix([(0.58, sweep(95, 40, 0.5) * env(0.5, 0.002, 7) * 1.2), (0.58, hp(noise(0.12), 800) * env(0.12, 0.0005, 45) * 0.8)], d)
f_hum = 100.0 * 0.2 ** np.clip((t - 0.62) / 1.9, 0, 1)
spin = np.sin(2 * np.pi * np.cumsum(f_hum) / SR) * np.interp(t, [0.6, 0.7, 2.6], [0.0, 0.5, 0.0])
fanrun = lp(noise(d), 700) * np.interp(t, [0, 0.58, 0.7, 2.5], [0.25, 0.25, 0.2, 0.0])
clunk = mix([(2.55, sweep(60, 30, 0.35) * env(0.35, 0.003, 12) * 0.7)], d)
save("cine_cut", np.tanh(1.5 * (lamp * 0.45 + crack * 0.7 + thunk + spin + fanrun + clunk)))

# chair kicked back: wheels scrape, a hard bump, a rattle
d = 1.6
scr = bpg(noise(d), 1100, 0.45) * np.interp(T(d), [0, 0.05, 0.5, 0.7], [0, 1, 0.5, 0.0]) * (0.7 + 0.3 * np.sin(2 * np.pi * 38 * T(d)))
bump = mix([(0.62, sweep(140, 60, 0.3) * env(0.3, 0.002, 10)), (0.62, lp(noise(0.2), 900) * env(0.2, 0.001, 25) * 0.8)], d)
rat = bpg(noise(d), 3000, 0.4) * np.interp(T(d), [0.62, 0.7, 1.4], [0, 0.5, 0]) * (np.sin(2 * np.pi * 26 * T(d)) > 0)
save("cine_chair", scr * 0.7 + bump + rat * 0.3)

# a sharp gasp: noisy inhale that rises in pitch, with a rough voiced edge
d = 1.0
t = T(d)
inhale = bpg(noise(d), 2200, 0.7) * np.interp(t, [0, 0.08, 0.45, 0.62], [0, 1, 0.8, 0.0]) + 0.25 * lp(saw(180 + 120 * t, d), 1200) * np.interp(t, [0, 0.1, 0.5, 0.62], [0, 1, 0.6, 0])
save("cine_gasp", reverb(inhale, 0.7, 0.2, 3000)[:int(SR * 1.4)], peak=0.7)

# PC wake: a fan that should not be spinning howls up, a CRT-like whine, three wrong beeps, low hum
d = 4.0
t = T(d)
fanup = bpg(noise(d), 700, 0.7) * np.interp(t, [0, 0.15, 1.2, 3.8], [0, 0.8, 1.0, 0.3])
fanup = fanup + np.concatenate([sweep(30, 210, 1.6) * np.linspace(0.2, 0.9, int(SR * 1.6)), sine(210, d - 1.6) * 0.5])[:len(t)] * 0.4
whine = sine(4200, d) * np.interp(t, [0, 0.2, 0.9, 3.8], [0, 0.25, 0.1, 0.0]) * (1 + 0.1 * np.sin(2 * np.pi * 7 * t))
beeps = np.zeros_like(t)
for k, (tt, f) in enumerate([(0.9, 880), (1.15, 660), (1.45, 1320)]):
    n = int(SR * 0.13); i = int(SR * tt)
    beeps[i:i + n] += np.sign(np.sin(2 * np.pi * f * np.arange(n) / SR)) * 0.25 * np.exp(-np.arange(n) / (SR * 0.12))
low = sine(55.0, d) * np.interp(t, [0, 0.3, 3.0, 4.0], [0, 0.9, 0.9, 0]) + 0.4 * sine(110.0, d)
thump = mix([(0.0, sweep(90, 35, 0.4) * env(0.4, 0.002, 7))], d)
save("cine_pcwake", np.tanh(1.2 * (fanup * 0.5 + whine + beeps + low * 0.7 + thump * 1.1)))

# text being typed on the screen by itself: dry terminal blips
d = 2.6
bl = np.zeros(int(SR * d))
tt = 0.0
while tt < d - 0.12:
    n = int(SR * 0.035); i = int(SR * tt)
    f = rng.choice([1320, 1480, 1175, 1568])
    bl[i:i + n] += np.sin(2 * np.pi * f * np.arange(n) / SR) * np.exp(-np.arange(n) / (SR * 0.02)) * rng.uniform(0.5, 1.0)
    tt += rng.choice([0.04, 0.04, 0.06, 0.09])
save("cine_blips", bl, peak=0.5)

# logo reveal: a sub drop, a reversed swell, a ghostly dissonant chord
d = 4.0
t = T(d)
rev = (lp(noise(1.6), 5000) * np.linspace(0, 1, int(SR * 1.6)) ** 3)
chord = sum(lp(tone(f, d), 2200) * a for f, a in [(220.0, 1.0), (233.1, 0.7), (329.6, 0.5), (466.2, 0.4)]) * np.sin(np.pi * np.clip(t / d, 0, 1)) ** 1.2
sub = sweep(130, 32, 2.5) * env(2.5, 0.01, 1.3)
glass = sum(sine(f, d) * np.exp(-1.5 * t) * a for f, a in [(1760, 0.3), (2349, 0.2), (2960, 0.15)]) * np.interp(t, [0, 1.5, 1.6], [0, 0, 1])
logo = mix([(0.0, rev * 0.8), (1.5, sub * 1.1), (1.4, chord * 0.5), (1.5, glass * 0.5)], d)
save("cine_logo", reverb(logo, 2.2, 0.35, 3000)[:int(SR * 5.0)])

# digital glitch: stuttering sample-and-hold, bitcrushed sweeps, hard gating
d = 1.8
t = T(d)
base = sweep(900, 80, d) * 0.5 + bpg(noise(d), 2400, 0.9) * 0.6 + saw(55.0, d) * 0.4
gate = np.zeros_like(t); pos = 0.0
while pos < d:
    seg = rng.uniform(0.015, 0.09); on = rng.random() < 0.6
    gate[(t >= pos) & (t < pos + seg)] = 1.0 if on else 0.0; pos += seg
sh = np.repeat(rng.uniform(-1, 1, len(t) // 90 + 1), 90)[:len(t)] * 0.5
save("cine_glitch", bitcrush(base, 4, 7) * gate + sh * gate * 0.4)

# riser: rising noise band + detuned cluster + accelerating tremolo (8 s)
d = 8.0
t = T(d)
nz = noise(d); out = np.zeros_like(t)
for lo, hi_ in [(0, 2), (2, 4), (4, 6), (6, 8)]:
    sl = slice(int(SR * lo), int(SR * hi_))
    fc = 200 * (4200 / 200) ** (((lo + hi_) * 0.5) / d)
    out[sl] = bpg(nz[sl], fc, 0.7)
tremolo = 0.6 + 0.4 * np.sin(2 * np.pi * np.cumsum(2 + 22 * (t / d) ** 2) / SR)
cluster = sum(np.sin(2 * np.pi * np.cumsum(f0 * (3.0 ** (t / d))) / SR) for f0 in (90, 94, 136))
riser = (out * 1.0 + cluster * 0.25) * tremolo * np.linspace(0.05, 1, len(t)) ** 2.2
save("cine_riser", riser, peak=0.8)

# pulled into the screen: a vacuum of filtered air, a descending then ascending swirl, a sub rumble
d = 4.0
t = T(d)
air = bpg(noise(d), 1800, 0.9)
sweep_fc = np.interp(t, [0, 1.5, 3.2, 4.0], [3200, 700, 300, 2600])
air_a = np.zeros_like(t)
for k in range(0, len(t), 2048):
    seg = slice(k, k + 2048)
    air_a[seg] = bpg(noise(2048 / SR), float(sweep_fc[min(k, len(t) - 1)]), 0.55)[:len(air_a[seg])]
swirl = np.sin(2 * np.pi * np.cumsum(np.interp(t, [0, 2.0, 3.8], [900, 200, 1400])) / SR) * 0.3
rumble = lp(noise(d), 120) * np.linspace(0.2, 1.4, len(t)) + sine(42, d) * np.linspace(0.1, 1.0, len(t)) * 0.8
pull = (air_a * np.interp(t, [0, 0.4, 3.4, 4.0], [0, 1, 1, 0.5]) + swirl * np.sin(np.pi * t / d) + rumble * 0.7)
save("cine_pull", pull)

# the transition into the game world: a massive low hit, a digital shatter, a long tail
d = 5.0
t = T(d)
boom = fit(sweep(150, 30, 1.8) * env(1.8, 0.002, 2.2), len(t)) + 0.7 * sine(36, d) * np.exp(-1.1 * t)
shatter = fit(bitcrush(hp(noise(1.5), 1200), 4, 4) * env(1.5, 0.001, 3.8) * 0.7 + hp(noise(1.5), 4000) * env(1.5, 0.0005, 18) * 0.6, len(t))
body = lp(noise(d), 500) * np.exp(-1.6 * t) * 0.8
imp = np.tanh(2.0 * mix([(0.0, boom), (0.0, shatter), (0.0, body)], d))
save("cine_impact", reverb(imp, 3.2, 0.35, 2400)[:int(SR * 6.0)], peak=0.95)

print("%-14s %7s %6s %6s" % ("file", "sec", "peak", "rms"))
tot = 0
for k, (dur, pk, rms) in LOUD.items():
    size = os.path.getsize(os.path.join(OUT, k + ".wav")); tot += size
    print("%-14s %7.2f %6.2f %6.3f   %5d KB" % (k, dur, pk, rms, size // 1024))
print("total %.2f MB" % (tot / 1048576))
